const translations: Record<string, string> = {

  // --- PaletteProvider ---
  "Activate hand tool": "激活抓手工具",
  "Activate lasso tool": "激活套索工具",
  "Activate create/remove space tool": "激活创建/删除空间工具",
  "Activate global connect tool": "激活全局连接工具",
  "Create start event": "创建开始事件",
  "Create intermediate/boundary event": "创建中间/边界事件",
  "Create end event": "创建结束事件",
  "Create gateway": "创建网关",
  "Create task": "创建任务",
  "Create data object reference": "创建数据对象引用",
  "Create data store reference": "创建数据存储引用",
  "Create expanded sub-process": "创建展开子流程",
  "Create pool/participant": "创建池/参与者",
  "Create group": "创建分组",

  // --- ContextPadProvider ---
  "Delete": "删除",
  "Add lane above": "在上方添加泳道",
  "Add lane below": "在下方添加泳道",
  "Divide into two lanes": "分成两条泳道",
  "Divide into three lanes": "分成三条泳道",
  "Append receive task": "追加接收任务",
  "Append message intermediate catch event": "追加消息中间捕获事件",
  "Append timer intermediate catch event": "追加定时中间捕获事件",
  "Append conditional intermediate catch event": "追加条件中间捕获事件",
  "Append signal intermediate catch event": "追加信号中间捕获事件",
  "Append compensation activity": "追加补偿活动",
  "Append end event": "追加结束事件",
  "Append gateway": "追加网关",
  "Append task": "追加任务",
  "Append intermediate/boundary event": "追加中间/边界事件",
  "Change element": "修改元素",
  "Add text annotation": "添加文本注释",
  "Connect to other element": "连接到其他元素",
  "Connect using association": "使用关联连接",
  "Connect using data input association": "使用数据输入关联连接",

  // --- ReplaceMenuProvider header entries ---
  "Parallel multi-instance": "并行多实例",
  "Sequential multi-instance": "串行多实例",
  "Loop": "循环",
  "Collection": "集合",
  "Participant multiplicity": "参与者多重性",
  "Toggle non-interrupting": "切换非中断",

  // --- ReplaceOptions: start events ---
  "Start event": "开始事件",
  "Intermediate throw event": "中间抛出事件",
  "End event": "结束事件",
  "Message start event": "消息开始事件",
  "Timer start event": "定时开始事件",
  "Conditional start event": "条件开始事件",
  "Signal start event": "信号开始事件",
  "Error start event": "错误开始事件",
  "Escalation start event": "升级开始事件",
  "Compensation start event": "补偿开始事件",
  "Message start event (non-interrupting)": "消息开始事件（非中断）",
  "Timer start event (non-interrupting)": "定时开始事件（非中断）",
  "Conditional start event (non-interrupting)": "条件开始事件（非中断）",
  "Signal start event (non-interrupting)": "信号开始事件（非中断）",
  "Escalation start event (non-interrupting)": "升级开始事件（非中断）",

  // --- ReplaceOptions: intermediate events ---
  "Message intermediate catch event": "消息中间捕获事件",
  "Message intermediate throw event": "消息中间抛出事件",
  "Timer intermediate catch event": "定时中间捕获事件",
  "Escalation intermediate throw event": "升级中间抛出事件",
  "Conditional intermediate catch event": "条件中间捕获事件",
  "Link intermediate catch event": "链接中间捕获事件",
  "Link intermediate throw event": "链接中间抛出事件",
  "Compensation intermediate throw event": "补偿中间抛出事件",
  "Signal intermediate catch event": "信号中间捕获事件",
  "Signal intermediate throw event": "信号中间抛出事件",

  // --- ReplaceOptions: end events ---
  "Message end event": "消息结束事件",
  "Escalation end event": "升级结束事件",
  "Error end event": "错误结束事件",
  "Cancel end event": "取消结束事件",
  "Compensation end event": "补偿结束事件",
  "Signal end event": "信号结束事件",
  "Terminate end event": "终止结束事件",

  // --- ReplaceOptions: gateways ---
  "Exclusive gateway": "互斥网关",
  "Parallel gateway": "并行网关",
  "Inclusive gateway": "相容网关",
  "Complex gateway": "复杂网关",
  "Event-based gateway": "事件网关",

  // --- ReplaceOptions: tasks / activities ---
  "Task": "任务",
  "User task": "用户任务",
  "Service task": "服务任务",
  "Send task": "发送任务",
  "Receive task": "接收任务",
  "Manual task": "手工任务",
  "Business rule task": "业务规则任务",
  "Script task": "脚本任务",
  "Call activity": "调用活动",

  // --- ReplaceOptions: sub-processes ---
  "Sub-process": "子流程",
  "Sub-process (collapsed)": "子流程（折叠）",
  "Sub-process (expanded)": "子流程（展开）",
  "Transaction": "事务",
  "Event sub-process": "事件子流程",
  "Ad-hoc sub-process": "即席子流程",
  "Ad-hoc sub-process (collapsed)": "即席子流程（折叠）",
  "Ad-hoc sub-process (expanded)": "即席子流程（展开）",

  // --- ReplaceOptions: data ---
  "Data object reference": "数据对象引用",
  "Data store reference": "数据存储引用",

  // --- ReplaceOptions: boundary events ---
  "Message boundary event": "消息边界事件",
  "Timer boundary event": "定时边界事件",
  "Escalation boundary event": "升级边界事件",
  "Conditional boundary event": "条件边界事件",
  "Error boundary event": "错误边界事件",
  "Cancel boundary event": "取消边界事件",
  "Signal boundary event": "信号边界事件",
  "Compensation boundary event": "补偿边界事件",
  "Message boundary event (non-interrupting)": "消息边界事件（非中断）",
  "Timer boundary event (non-interrupting)": "定时边界事件（非中断）",
  "Escalation boundary event (non-interrupting)": "升级边界事件（非中断）",
  "Conditional boundary event (non-interrupting)": "条件边界事件（非中断）",
  "Signal boundary event (non-interrupting)": "信号边界事件（非中断）",

  // --- ReplaceOptions: sequence flows ---
  "Sequence flow": "顺序流",
  "Default flow": "默认流",
  "Conditional flow": "条件流",

  // --- ReplaceOptions: participants ---
  "Expanded pool/participant": "展开池/参与者",
  "Empty pool/participant": "空池/参与者",
  " (removes content)": "（移除内容）",

  // --- AlignElementsMenuProvider ---
  "Align elements left": "左对齐",
  "Align elements center": "水平居中",
  "Align elements right": "右对齐",
  "Align elements top": "顶部对齐",
  "Align elements middle": "垂直居中",
  "Align elements bottom": "底部对齐",

  // --- DistributeElementsMenuProvider ---
  "Distribute elements horizontally": "水平分布",
  "Distribute elements vertically": "垂直分布",

  // --- 错误提示 ---
  "no parent for {element} in {parent}": "{element} 在 {parent} 中没有父元素",
  "no shape type specified": "未指定形状类型",
  "flow elements must be children of pools/participants": "流元素必须是池/参与者的子元素",
  "out of bounds release": "超出边界释放",
  "more than {count} child lanes": "子泳道超过 {count} 条",
  "element required": "缺少元素",
  "diagram not part of bpmn:Definitions": "流程图不符合 BPMN 规范",
  "no diagram to display": "没有可展示的流程图",
  "no process or collaboration to display": "没有可展示的流程/协作",
  "element {element} referenced by {referenced}#{property} not yet drawn":
    "由 {referenced}#{property} 引用的 {element} 尚未绘制",
  "already rendered {element}": "{element} 已渲染",
  "failed to import {element}": "导入 {element} 失败",

  // --- 属性面板相关 ---
  "Id": "编号",
  "Name": "名称",
  "General": "常规",
  "Details": "详情",
  "Message Name": "消息名称",
  "Message": "消息",
  "Initiator": "发起人",
  "Asynchronous Continuations": "异步执行",
  "Asynchronous Before": "异步前",
  "Asynchronous After": "异步后",
  "Job Configuration": "任务配置",
  "Exclusive": "独占",
  "Job Priority": "任务优先级",
  "Retry Time Cycle": "重试时间周期",
  "Documentation": "文档",
  "Element Documentation": "元素文档",
  "History Configuration": "历史配置",
  "History Time To Live": "历史保留时间",
  "Forms": "表单",
  "Form Key": "表单 Key",
  "Form Fields": "表单字段",
  "Business Key": "业务 Key",
  "Form Field": "表单字段",
  "ID": "编号",
  "Type": "类型",
  "Label": "标签",
  "Default Value": "默认值",
  "Validation": "校验",
  "Add Constraint": "添加约束",
  "Config": "配置",
  "Properties": "属性",
  "Add Property": "添加属性",
  "Value": "值",
  "Listeners": "监听器",
  "Execution Listener": "执行监听",
  "Event Type": "事件类型",
  "Listener Type": "监听器类型",
  "Java Class": "Java 类",
  "Expression": "表达式",
  "Must provide a value": "必须提供一个值",
  "Delegate Expression": "代理表达式",
  "Script": "脚本",
  "Script Format": "脚本格式",
  "Script Type": "脚本类型",
  "Inline Script": "内联脚本",
  "External Script": "外部脚本",
  "Resource": "资源",
  "Field Injection": "字段注入",
  "Extensions": "扩展",
  "Input/Output": "输入/输出",
  "Input Parameters": "输入参数",
  "Output Parameters": "输出参数",
  "Parameters": "参数",
  "Output Parameter": "输出参数",
  "Timer Definition Type": "定时器定义类型",
  "Timer Definition": "定时器定义",
  "Date": "日期",
  "Duration": "持续时间",
  "Cycle": "循环",
  "Signal": "信号",
  "Signal Name": "信号名称",
  "Escalation": "升级",
  "Error": "错误",
  "Link Name": "链接名称",
  "Condition": "条件",
  "Variable Name": "变量名称",
  "Variable Event": "变量事件",
  "Specify more than one variable change event as a comma separated list.": "多个变量事件以逗号分隔。",
  "Wait for Completion": "等待完成",
  "Activity Ref": "活动引用",
  "Version Tag": "版本标签",
  "Executable": "可执行",
  "External Task Configuration": "外部任务配置",
  "Task Priority": "任务优先级",
  "External": "外部",
  "Connector": "连接器",
  "Must configure Connector": "必须配置连接器",
  "Connector Id": "连接器编号",
  "Implementation": "实现方式",
  "Field Injections": "字段注入",
  "Fields": "字段",
  "Result Variable": "结果变量",
  "Topic": "主题",
  "Configure Connector": "配置连接器",
  "Input Parameter": "输入参数",
  "Assignee": "办理人",
  "Candidate Users": "候选用户",
  "Candidate Groups": "候选组",
  "Due Date": "到期时间",
  "Follow Up Date": "跟进时间",
  "Priority": "优先级",
  "Variables": "变量",
  "Candidate Starter Configuration": "候选启动配置",
  "Candidate Starter Groups": "候选启动组",
  "This maps to the process definition key.": "映射到流程定义 Key。",
  "Candidate Starter Users": "候选启动用户",
  "Specify more than one user as a comma separated list.": "多个用户以逗号分隔。",
  "Tasklist Configuration": "任务列表配置",
  "Startable": "可启动",
  "Specify more than one group as a comma separated list.": "多个组以逗号分隔。",
};

export default translations;
